# References:
# https://nuxt.com/deploy/github-pages
# https://github.com/actions/deploy-pages#usage

name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blog
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: './blog/package-lock.json'
      - name: Audit dependencies
        run: npm audit --audit-level info
      - name: Install dependencies
        run: npm install
      - name: Build static website
        run: NUXT_APP_BASE_URL=/eddiecorrigall.github.io/ npx nuxt build --preset github_pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./blog/.output/public/

  deploy:
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
