# References:
# https://nuxt.com/deploy/github-pages
# https://github.com/actions/deploy-pages#usage
# https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages
# https://github.com/actions/starter-workflows/blob/main/pages/nuxtjs.yml

name: Deploy to GitHub Pages
on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blog
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: './blog/package-lock.json'
      - name: Audit dependencies
        run: npm audit --audit-level info
      - name: Setup pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: nuxt
      - name: Install dependencies
        run: npm install
      - name: Build static website
        run: NUXT_APP_BASE_URL=/eddiecorrigall.github.io/ npm run generate
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
