# References:
# https://github.com/actions/deploy-pages#usage
# https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages

name: 'Hugo: Deploy to GitHub Pages'
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/hugo-deploy.yaml
      - frontend/**
      - hugo/**
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-js:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: './frontend/package-lock.json'
      - name: Audit dependencies
        run: npm audit --audit-level info
      - name: Install dependencies
        run: npm clean-install
      - name: Build artifact
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: js
          path: frontend/dist
          if-no-files-found: error
          retention-days: 3

  build-www:
    needs: build-js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hugo
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.127.0'
          # https://gohugo.io/installation/linux/#editions
          # WebP format for image compression and Sass to CSS
          extended: true

      - name: Build static website
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
         path: ./hugo/public

  deploy:
    needs: build-www
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
